#!/bin/sh

cd data &&
php -d pcov.enabled=1 ../phpunit/vendor/bin/phpunit --configuration /app/configs/phpunit.xml &&
../php-cs-fixer/vendor/bin/php-cs-fixer --dry-run --allow-risky=yes --diff --no-interaction --ansi --using-cache=no --config=/app/configs/.php-cs-fixer.php fix src &&
../phpstan/vendor/bin/phpstan --memory-limit=512M analyze -c /app/configs/phpstan.neon src