#!/bin/sh

cd data &&
../rector/vendor/bin/rector process src &&
../php-cs-fixer/vendor/bin/php-cs-fixer --diff --no-interaction --ansi --using-cache=no fix src &&
../phpstan/vendor/bin/phpstan --memory-limit=512M analyze src