#!/bin/bash

cd /app/data &&
echo 'Rector source code' &&
echo '------------------' &&
../rector/vendor/bin/rector process --config=/app/configs/rector.php src &&
echo 'Rector tests code' &&
echo '------------------' &&
../rector/vendor/bin/rector process --config=/app/configs/rector.php tests &&
echo 'CS Fixer' &&
echo '--------' &&
../php-cs-fixer/vendor/bin/php-cs-fixer fix --diff --no-interaction --ansi --using-cache=no --config=/app/configs/.php-cs-fixer.php src  &&
echo 'PHP Stan' &&
echo '--------' &&
../phpstan/vendor/bin/phpstan --memory-limit=512M analyze -c /app/configs/phpstan.neon src