#!/bin/bash

echo 'CS Fixer' &&
echo '--------'

if ! (/app/php-cs-fixer/vendor/bin/php-cs-fixer --dry-run --allow-risky=yes --diff --no-interaction --ansi --using-cache=no --config=/app/configs/.php-cs-fixer.pipeline.php fix /opt/atlassian/pipelines/agent/build/src)
then
        echo "CS FIXER failed"
        echo "---------------"
        exit 1
fi

echo 'PHP Stan' &&
echo '--------'

if ! (/app/phpstan/vendor/bin/phpstan --memory-limit=512M analyze -c /app/configs/phpstan.neon /opt/atlassian/pipelines/agent/build/src)
then
        echo "PHPSTAN failed"
        echo "--------------"
        exit 1
fi

echo 'PHP Unit' &&
echo '--------'

if ! (php -d pcov.enabled=1 /app/phpunit/vendor/bin/phpunit --configuration /app/configs/phpunit-pipeline.xml)
then
        echo "PHPUnit failed"
        echo "--------------"
        exit 1
fi

exit 0